In [7]:
import numpy as np
from Tablero import Tablero
from Timbiriche import Timbiriche
def rot90(board):
    rot = np.copy(board)
    n = board.shape[0]
    for i in range(n):
        rot[:,-i-1] = board[i]

    for y in range(n):
        for x in range(n):
            pos = rot[y,x]
            if pos == 1:
                rot[y,x] = 2
            elif pos == 2:
                rot[y,x] = 1
            if pos in [2,3]:
                rot[y,x] -= 1
                rot[y-1,x] += 1
    return rot


tab1 = Tablero(5)
tab1.mover(1,1,2)
tab1.mover(1,2,1)
tab1.mover(3,2,2)
tab1.mover(4,2,2)
tab2 = Tablero(5)
tab2.tablero = rot90(tab1.tablero)
print(tab1), print(tab2)
np.array_str(tab1.tablero)


4. . ._. . 
3. . ._. . 
2. . . . . 
1. ._| . . 
0. . . . . 
 0 1 2 3 4 

4. . . . . 
3. . . . . 
2. . . ._. 
1| | . . . 
0. . . | . 
 0 1 2 3 4 


'[[0 0 0 0 0]\n [0 2 1 0 0]\n [0 0 0 0 0]\n [0 0 2 0 0]\n [0 0 2 0 0]]'

In [1]:
a,b = [1,2]
a

1

In [4]:
tab1 = Tablero(4)
tab1.mover(1,1,2)
tab1.mover(1,2,1)
tab1.mover(1,2,2)
tab1.mover(0,0,2)
tab1.mover(0,0,1)
tab1.mover(3,2,2)
tab1.mover(2,3,1)

def rot(tab):
    # Rotación +90 según mano derecha
    n = tab.n
    tab2 = Tablero(n)
    for y in range(n):
        for x in range(n):
            prev = tab[y,x]
            if prev == 1:
                tab2[x,n-y-2] += 2
            if prev == 2:
                tab2[x,n-y-1] += 1
            if prev == 3:
                tab2[x,n-y-2] += 2
                tab2[x,n-y-1] += 1
    return tab2

tab2 = rot(tab1)
print(tab1), print(tab2)


3. . ._. 
2. . . | 
1. ._|_. 
0|_. . . 
 0 1 2 3 

3._. . . 
2| ._| . 
1. . | . 
0. . ._| 
 0 1 2 3 


(None, None)

In [37]:
acts = []
n = 5
for y in range(n):
    for x in range(n):
        acts.append((y,x,1))
        acts.append((y,x,2))
actsrot = []
for y in range(n):
    for x in range(n):
        actsrot.append((x,n-y-2,2))
        actsrot.append((x,n-y-1,1))
actmat = np.reshape(acts, (n, n, 2, 3))
rotmat = np.reshape(actsrot, (n, n, 2, 3))
def rotpol(pol):
    #   Rotación correspondiente del vector p
    polmat = np.reshape(pol, (n, n, 2))
    newmat = np.zeros((n, n, 2))
    for i in range(n):
        for j in range(n):
            newmat[n-j-1, i, 1] = polmat[i, j, 0]
            newmat[n-j-2, i, 0] = polmat[i, j, 1]
    return np.uint8(newmat.flatten())


pol = range(n*n*2)
#acts.index(tuple(rotmat[0,0,0,:]))
#rotmat[::-1,0,0,:]
rotmat[0,:,:,:]

# rotacts = []
# for i in range(n):
#     for j in range(n):
#         for m in range(2):
#             rotacts.append(tuple(rotmat(i,j,m,:)))

rotp = rotpol(list(range(2*n**2)))


tab1 = Tablero(n)
tab2 = Tablero(n)
# for i in[1, 4, 6, 7]:
#     tab1.mover(*acts[i])
#     tab2.mover(*actsrot[i])
# Obj: F: pol_acts [0,0,1] -> pol_rot [0, 3, 2]
actmat[:, -1, ::-1, :]

for i in [3, 5, 6, 7, 8, 9, 12, 15, 17, 45]:
    tab1.mover(*acts[i])
    tab2.mover(*acts[rotp[i]])
print(tab1), print(tab2)



4. . ._. . 
3. . . . . 
2. . . . . 
1. | ._._. 
0. ._._|_| 
 0 1 2 3 4 

4. . . ._. 
3. . . |_| 
2| . . | | 
1. . ._. | 
0. . . . . 
 0 1 2 3 4 


(None, None)

In [38]:
n = 5

def rot90(tab, n):
    # Rotación de tablero +90 según mano derecha
    rot_tab = Tablero(n)
    for y in range(n):
        for x in range(n):
            prev = tab[y,x]
            if prev == 1:
                rot_tab[x,n-y-2] += 2
            if prev == 2:
                rot_tab[x,n-y-1] += 1
            if prev == 3:
                rot_tab[x,n-y-2] += 2
                rot_tab[x,n-y-1] += 1
    return rot_tab.tablero

def rot_pol90(pol, n):
    # Rotación correspondiente del vector pi
    polmat = np.reshape(pol, (n, n, 2))
    newmat = np.zeros((n, n, 2))
    for i in range(n):
        for j in range(n):
            newmat[n-j-1, i, 1] = polmat[i, j, 0]
            newmat[n-j-2, i, 0] = polmat[i, j, 1]
    return newmat.flatten()

def reflect(tab, n):
    # Reflejar respecto eje x
    ref_tab = Tablero(n)
    for y in range(n):
        for x in range(n):
            prev = tab[y,x]
            if prev == 1:
                ref_tab[n-y-2, x] += 1
            if prev == 2:
                ref_tab[n-y-1, x] += 2
            if prev == 3:
                ref_tab[n-y-2, x] += 1
                ref_tab[n-y-1, x] += 2
    return ref_tab.tablero

def reflect_pol(pol, n):
    # Reflexión correspondiente de vector pi
    polmat = np.reshape(pol, (n, n, 2))
    newmat = np.zeros((n, n, 2))
    for i in range(n):
        for j in range(n):
            newmat[n-i-2, j, 0] = polmat[i, j, 0]
            newmat[n-i-1, j, 1] = polmat[i, j, 1]
    return newmat.flatten()

pol = list(range(2*n**2))
refp = np.uint8(rot_pol90(pol, n))

tab1 = Tablero(n)
# tab1.mover(1,1,2)
# tab1.mover(1,2,1)
# tab1.mover(1,2,2)
# tab1.mover(0,0,2)
tab2 = Tablero(n)
# tab2.tablero = reflect(tab1, n)

for i in [1, 2, 3, 4, 45]:
    tab1.mover(*acts[i])
    tab2.mover(*acts[refp[i]])

print(tab1), print(tab2)


4. . ._. . 
3. . . . . 
2. . . . . 
1. . . . . 
0._|_| . . 
 0 1 2 3 4 

4. . . . . 
3. . . . . 
2| . . ._. 
1. . . ._| 
0. . . . | 
 0 1 2 3 4 


(None, None)

In [9]:
rotmat[0, :, :, :]

array([[[0, 3, 2],
        [0, 4, 1]],

       [[1, 3, 2],
        [1, 4, 1]],

       [[2, 3, 2],
        [2, 4, 1]],

       [[3, 3, 2],
        [3, 4, 1]],

       [[4, 3, 2],
        [4, 4, 1]]])

In [2]:
import torch
from torch import nn
c = 64
n = 5
convnet = nn.Sequential(
    nn.Conv2d(1, c, 3, padding='SAME'),
    nn.BatchNorm2d(c),
    nn.ReLU(),
    nn.Conv2d(c, c, 3, padding='SAME'),
    nn.BatchNorm2d(c),
    nn.ReLU()) # Salida: ()

p_head = nn.Sequential(
    nn.Conv2d(c, 2, 1),
    nn.BatchNorm2d(2),
    nn.Flatten(start_dim=1),
    nn.Linear(2*n**2, 2*n**2),
    nn.Softmax()) # Activación final con salida [0,1] y suma=1

v_head = nn.Sequential(
    nn.Conv2d(c, 1, 1),
    nn.BatchNorm2d(1), #BN1D después de flatten?
    nn.Flatten(start_dim=1),
    nn.Linear(n**2 , 1),
    nn.Tanh())

model = nn.Sequential(
    convnet,
    p_head
)

sum(p.numel() for p in model.parameters())

40508

In [49]:
from Timbiriche import Tablero, Timbiriche
tab1 = Tablero(5)
tab1.mover(1,1,2)
tab1.mover(1,2,1)
tab1.mover(3,2,2)
tab1.mover(4,2,2)

g = Timbiriche(5)
g.getValidMoves(tab1.tablero, 1)[20], g.actions[20]

(1, (2, 0, 1))

In [8]:
import torch
import numpy as np

a = {}
s = '1236'
b = torch.FloatTensor([0.4124, 0.6363, 0.345262])
a[s] = b
a[s] = a[s] * np.array([False, True, False], dtype=np.uint8)
torch.sum(a[s])

tensor(0.6363)

In [9]:
import torch
from torch import nn
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)
input.shape, input.unsqueeze_(dim=1).shape

(torch.Size([2, 3]), torch.Size([2, 1, 3]))

In [6]:
import torch
from torch.utils.data import Dataset, DataLoader

data = []
for i in range(64):
    a = torch.rand((2,2))
    b = torch.rand(4)
    c = torch.rand(1).item()
    data.append((a,b,c))

data

[(tensor([[0.5301, 0.4175],
          [0.3744, 0.7752]]),
  tensor([0.9239, 0.7559, 0.8992, 0.7146]),
  0.1183972954750061),
 (tensor([[0.2052, 0.7585],
          [0.0491, 0.6261]]),
  tensor([0.8648, 0.9329, 0.6224, 0.0378]),
  0.2734188437461853),
 (tensor([[0.0334, 0.0909],
          [0.1767, 0.6305]]),
  tensor([0.4363, 0.0839, 0.5233, 0.3826]),
  0.10066443681716919),
 (tensor([[0.3298, 0.9911],
          [0.3823, 0.0271]]),
  tensor([0.7836, 0.6291, 0.9605, 0.1046]),
  0.3371305465698242),
 (tensor([[0.7134, 0.7390],
          [0.3319, 0.6254]]),
  tensor([0.7151, 0.4093, 0.7993, 0.2998]),
  0.1093062162399292),
 (tensor([[0.4422, 0.6856],
          [0.7549, 0.4617]]),
  tensor([0.2027, 0.2416, 0.9755, 0.7430]),
  0.03489649295806885),
 (tensor([[0.5099, 0.1195],
          [0.1102, 0.1475]]),
  tensor([0.0889, 0.9893, 0.7129, 0.2870]),
  0.2894860506057739),
 (tensor([[0.6561, 0.3748],
          [0.2570, 0.9061]]),
  tensor([0.2959, 0.6426, 0.1787, 0.2207]),
  0.8695873618125916)

In [40]:
import torch
from torch import nn
#torch.manual_seed(42)
a = torch.rand((4,6))
b = torch.argmax(a, dim=1)#.unsqueeze(dim=1)
loss = nn.CrossEntropyLoss()
c = torch.randint(0, 5, (4,))
a, b, c, loss(a, b), loss(a, c)

(tensor([[0.7216, 0.6107, 0.5989, 0.1208, 0.0331, 0.5088],
         [0.9559, 0.7885, 0.2089, 0.4351, 0.1314, 0.2588],
         [0.5905, 0.7723, 0.9142, 0.0409, 0.8343, 0.1474],
         [0.6872, 0.9231, 0.5070, 0.9549, 0.0740, 0.3090]]),
 tensor([0, 0, 2, 3]),
 tensor([4, 1, 2, 0]),
 tensor(1.4562),
 tensor(1.7371))